Update bootify

diff --git a/bootify b/bootify
--- a/bootify
+++ b/bootify
@@ -104,7 +104,7 @@ partitioning() {
     parted -s -a optimal $DEV mklabel msdos mkpart primary ntfs 1 100% set 1 boot
     mkfs.ntfs -f -L BOOTIFY ${DEV}1
     echo -n -e '\x33\xc0\xfa\x8e\xd8\x8e\xd0\xbc\x00\x7c\x89\xe6\x06\x57\x8e\xc0\xfb\xfc\xbf\x00\x06\xb9\x00\x01\xf3\xa5\xea\x1f\x06\x00\x00\x52\x52\xb4\x41\xbb\xaa\x55\x31\xc9\x30\xf6\xf9\xcd\x13\x72\x13\x81\xfb\x55\xaa\x75\x0d\xd1\xe9\x73\x09\x66\xc7\x06\x8d\x06\xb4\x42\xeb\x15\x5a\xb4\x08\xcd\x13\x83\xe1\x3f\x51\x0f\xb6\xc6\x40\xf7\xe1\x52\x50\x66\x31\xc0\x66\x99\xe8\x66\x00\xe8\x35\x01\x4d\x69\x73\x73\x69\x6e\x67\x20\x6f\x70\x65\x72\x61\x74\x69\x6e\x67\x20\x73\x79\x73\x74\x65\x6d\x2e\x0d\x0a\x66\x60\x66\x31\xd2\xbb\x00\x7c\x66\x52\x66\x50\x06\x53\x6a\x01\x6a\x10\x89\xe6\x66\xf7\x36\xf4\x7b\xc0\xe4\x06\x88\xe1\x88\xc5\x92\xf6\x36\xf8\x7b\x88\xc6\x08\xe1\x41\xb8\x01\x02\x8a\x16\xfa\x7b\xcd\x13\x8d\x64\x10\x66\x61\xc3\xe8\xc4\xff\xbe\xbe\x7d\xbf\xbe\x07\xb9\x20\x00\xf3\xa5\xc3\x66\x60\x89\xe5\xbb\xbe\x07\xb9\x04\x00\x31\xc0\x53\x51\xf6\x07\x80\x74\x03\x40\x89\xde\x83\xc3\x10\xe2\xf3\x48\x74\x5b\x79\x39\x59\x5b\x8a\x47\x04\x3c\x0f\x74\x06\x24\x7f\x3c\x05\x75\x22\x66\x8b\x47\x08\x66\x8b\x56\x14\x66\x01\xd0\x66\x21\xd2\x75\x03\x66\x89\xc2\xe8\xac\xff\x72\x03\xe8\xb6\xff\x66\x8b\x46\x1c\xe8\xa0\xff\x83\xc3\x10\xe2\xcc\x66\x61\xc3\xe8\x76\x00\x4d\x75\x6c\x74\x69\x70\x6c\x65\x20\x61\x63\x74\x69\x76\x65\x20\x70\x61\x72\x74\x69\x74\x69\x6f\x6e\x73\x2e\x0d\x0a\x66\x8b\x44\x08\x66\x03\x46\x1c\x66\x89\x44\x08\xe8\x30\xff\x72\x27\x66\x81\x3e\x00\x7c\x58\x46\x53\x42\x75\x09\x66\x83\xc0\x04\xe8\x1c\xff\x72\x13\x81\x3e\xfe\x7d\x55\xaa\x0f\x85\xf2\xfe\xbc\xfa\x7b\x5a\x5f\x07\xfa\xff\xe4\xe8\x1e\x00\x4f\x70\x65\x72\x61\x74\x69\x6e\x67\x20\x73\x79\x73\x74\x65\x6d\x20\x6c\x6f\x61\x64\x20\x65\x72\x72\x6f\x72\x2e\x0d\x0a\x5e\xac\xb4\x0e\x8a\x3e\x62\x04\xb3\x07\xcd\x10\x3c\x0a\x75\xf1\xcd\x18\xf4\xeb\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /tmp/mbr.bin
-    dd if=/tmp/mbr.bin of=$DEV > /dev/null 2>&1 || error "Error injecting mbr"
+    dd if=/tmp/mbr.bin of=$DEV > /dev/null 2>&1 || error "Error writing mbr"
   elif [[ "$SCH" == "uefi" ]]; then
     parted -s -a optimal $DEV mklabel gpt mkpart primary fat32 1 100%
     mkfs.vfat -F32 -n BOOTIFY ${DEV}1
